---
- name: Deploy Docker Container
  hosts: web
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Pull Docker image
      command: docker pull yasinio/assignment2-app:{{ image_tag }}

    - name: Stop old container if running
      command: docker stop assignment2-app
      ignore_errors: yes

    - name: Remove old container if present
      command: docker rm assignment2-app
      ignore_errors: yes

    - name: Run container
      command: docker run -d --name assignment2-app -p 80:80 yasinio/assignment2-app:{{ image_tag }}
